stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t booking-service:latest -f booking-service/Dockerfile booking-service/
    - minikube image load booking-service:latest

test:
  stage: test
  script:
    - docker run --rm -d -p 8080:8080 --name test booking-service:latest
    - sleep 3
    - curl http://localhost:8080/ping | grep pong

deploy:
  stage: deploy
  script:
    - helm upgrade --install booking-service ./helm/booking-service -f ./helm/booking-service/values-stage.yaml
    - kubectl get pods
